version: '3.8'

services:
  openjdk11:
    build: .
    container_name: openjdk11_container
    ports:
      - "9870:9870"
      - "8088:8088"
    networks:
      - openjdk_network

networks:
  openjdk_network:
    driver: bridge
